/* ==========================================================================
   FitTrack — Dados semente (biblioteca de exercícios, treinos, conquistas)
   ========================================================================== */

const MUSCLE_ICONS = {
  peito:'💪', costas:'🏋️', pernas:'🦵', gluteos:'🍑', ombros:'🤸',
  biceps:'💪', triceps:'💪', abdomen:'🔥', cardio:'🏃'
};

const EXERCISE_LIBRARY = [
  {id:'ex_supino', name:'Supino Reto', muscle:'peito', desc:'Exercício composto para desenvolvimento do peitoral maior, usando barra ou halteres deitado no banco.',
    execution:'Deite no banco, pés firmes no chão, desça a barra até tocar levemente o peito e empurre de volta explosivamente, sem travar os cotovelos.',
    mistakes:'Arquear demais a lombar, descer a barra rápido demais e usar amplitude incompleta.'},
  {id:'ex_supino_halteres', name:'Supino com Halteres', muscle:'peito', desc:'Variação do supino com halteres, permite maior amplitude e ativação estabilizadora.',
    execution:'Deitado no banco, desça os halteres ao lado do peito controlando o movimento e empurre para cima sem travar os cotovelos.',
    mistakes:'Deixar os halteres se chocarem no topo e perder o alinhamento dos punhos.'},
  {id:'ex_supino_maquina', name:'Supino Máquina', muscle:'peito', desc:'Exercício guiado para peitoral com menor exigência de estabilização.',
    execution:'Ajuste o banco na altura correta, empurre os manípulos à frente sem travar os cotovelos e retorne controlado.',
    mistakes:'Ajustar o banco na altura errada, sobrecarregando o ombro.'},
  {id:'ex_supino_inclinado', name:'Supino Inclinado', muscle:'peito', desc:'Trabalha a porção superior do peitoral com o banco inclinado entre 30-45°.',
    execution:'Ajuste o banco a 30-45°, controle a descida até a linha da clavícula e empurre para cima.',
    mistakes:'Inclinar demais o banco (vira ombro) e usar carga excessiva perdendo a técnica.'},
  {id:'ex_crucifixo', name:'Crucifixo', muscle:'peito', desc:'Isolamento do peitoral com halteres, foco no alongamento e contração.',
    execution:'Braços levemente flexionados, abra os halteres em arco até sentir alongamento e retorne contraindo o peito.',
    mistakes:'Flexionar totalmente o cotovelo (vira supino) e descer além do conforto do ombro.'},
  {id:'ex_crucifixo_maquina', name:'Crucifixo Máquina (Peck Deck)', muscle:'peito', desc:'Isolamento do peitoral em máquina, ótimo para controlar a amplitude com segurança.',
    execution:'Sentado, junte os apoios à frente do peito contraindo o peitoral e retorne controlado até o alongamento.',
    mistakes:'Usar impulso do tronco para frente e amplitude excessiva forçando o ombro.'},
  {id:'ex_puxada', name:'Puxada Frontal', muscle:'costas', desc:'Exercício de puxada vertical para desenvolvimento do latíssimo do dorso.',
    execution:'Puxe a barra em direção à parte superior do peito, contraindo as escápulas, e controle a subida.',
    mistakes:'Usar impulso do corpo e puxar atrás da nuca, o que sobrecarrega o ombro.'},
  {id:'ex_remada', name:'Remada Curvada', muscle:'costas', desc:'Trabalha espessura das costas com barra ou halteres em posição inclinada.',
    execution:'Tronco inclinado a 45°, puxe o peso em direção ao abdômen mantendo a coluna neutra.',
    mistakes:'Arredondar as costas e usar balanço excessivo do tronco.'},
  {id:'ex_remada_baixa', name:'Remada Baixa', muscle:'costas', desc:'Exercício de puxada horizontal em polia baixa para espessura das costas.',
    execution:'Sentado, puxe o cabo até o abdômen mantendo o tronco ereto e escápulas retraídas.',
    mistakes:'Balançar o tronco para trás e encolher os ombros durante o movimento.'},
  {id:'ex_remada_unilateral', name:'Remada Unilateral', muscle:'costas', desc:'Exercício com halter apoiado no banco, permite foco individual em cada lado das costas.',
    execution:'Apoie joelho e mão no banco, puxe o halter em direção ao quadril mantendo o cotovelo próximo ao corpo.',
    mistakes:'Girar o tronco para ajudar o movimento em vez de usar as costas.'},
  {id:'ex_pullover_cabo', name:'Pullover no Cabo', muscle:'costas', desc:'Exercício de isolamento para o latíssimo do dorso usando a polia alta.',
    execution:'Com os braços quase estendidos, puxe o cabo em arco até a altura das coxas contraindo as costas.',
    mistakes:'Flexionar demais os cotovelos, transformando o movimento em exercício de tríceps.'},
  {id:'ex_agachamento', name:'Agachamento Livre', muscle:'pernas', desc:'Exercício fundamental para quadríceps, glúteos e posteriores.',
    execution:'Pés na largura dos ombros, desça controlando o quadril para trás até coxas paralelas ao chão e suba.',
    mistakes:'Joelhos colapsando para dentro e perder a curvatura natural da lombar.'},
  {id:'ex_agachamento_smith', name:'Agachamento no Smith', muscle:'pernas', desc:'Agachamento guiado pela máquina Smith, com maior estabilidade e segurança de carga.',
    execution:'Posicione a barra sobre os trapézios, desça controlado até 90° de joelho e suba sem travar.',
    mistakes:'Posicionar os pés muito próximos da barra, sobrecarregando os joelhos.'},
  {id:'ex_agachamento_sumo', name:'Agachamento Sumô', muscle:'gluteos', desc:'Variação com pernas afastadas e pés rotacionados, prioriza glúteos e adutores.',
    execution:'Pés bem afastados e rotacionados para fora, desça mantendo os joelhos alinhados com os pés e suba contraindo o glúteo.',
    mistakes:'Deixar o tronco inclinar demais para frente e joelhos ultrapassarem a linha dos pés.'},
  {id:'ex_agachamento_bulgaro', name:'Agachamento Búlgaro', muscle:'gluteos', desc:'Exercício unilateral com o pé de trás apoiado, forte estímulo de glúteo e quadríceps.',
    execution:'Apoie o peito do pé de trás em um banco, desça o joelho da frente controlado e suba contraindo o glúteo.',
    mistakes:'Dar um passo curto demais, sobrecarregando o joelho da frente.'},
  {id:'ex_leg_press', name:'Leg Press', muscle:'pernas', desc:'Exercício guiado para quadríceps e glúteos com menor exigência de estabilização.',
    execution:'Posicione os pés na plataforma, desça controlado até 90° de flexão de joelho e empurre sem travar.',
    mistakes:'Descer demais tirando o quadril do encosto e travar os joelhos no topo.'},
  {id:'ex_cadeira_extensora', name:'Cadeira Extensora', muscle:'pernas', desc:'Isolamento do quadríceps na máquina extensora.',
    execution:'Sentado, estenda os joelhos contraindo o quadríceps no topo e desça controlado sem soltar o peso.',
    mistakes:'Usar impulso e soltar a carga rapidamente na descida.'},
  {id:'ex_stiff', name:'Stiff', muscle:'pernas', desc:'Exercício de cadeia posterior para posteriores de coxa e glúteos, feito com barra ou halteres.',
    execution:'Pernas levemente flexionadas, desça o peso próximo às pernas mantendo a coluna reta até sentir alongamento.',
    mistakes:'Curvar as costas e afastar demais o peso do corpo.'},
  {id:'ex_levantamento_romeno', name:'Levantamento Terra Romeno (RDL)', muscle:'pernas', desc:'Variação do stiff com maior amplitude no quadril, foco em posteriores e glúteos.',
    execution:'Empurre o quadril para trás mantendo a barra próxima às pernas, desça até sentir alongamento no posterior e retorne contraindo o glúteo.',
    mistakes:'Perder a curvatura neutra da coluna e flexionar demais os joelhos.'},
  {id:'ex_mesa_flexora', name:'Mesa Flexora', muscle:'pernas', desc:'Isolamento dos posteriores de coxa deitado na máquina flexora.',
    execution:'Deitado de bruços, flexione os joelhos trazendo o rolo em direção ao glúteo e desça controlado.',
    mistakes:'Elevar o quadril da mesa durante o movimento para compensar a carga.'},
  {id:'ex_cadeira_flexora', name:'Cadeira Flexora', muscle:'pernas', desc:'Isolamento dos posteriores de coxa sentado na máquina flexora.',
    execution:'Sentado, flexione os joelhos puxando o rolo para baixo e retorne controlado até a extensão.',
    mistakes:'Usar amplitude incompleta e soltar o peso rapidamente na volta.'},
  {id:'ex_afundo', name:'Afundo', muscle:'gluteos', desc:'Exercício unilateral para glúteos e quadríceps, ótimo para equilíbrio muscular.',
    execution:'De pé, dê um passo à frente e desça o joelho de trás quase tocando o chão, volte à posição inicial.',
    mistakes:'Deixar o joelho da frente ultrapassar muito a ponta do pé de forma instável.'},
  {id:'ex_afundo_andando', name:'Afundo Andando', muscle:'gluteos', desc:'Variação dinâmica do afundo, alternando as pernas a cada passo.',
    execution:'Dê um passo à frente descendo o joelho de trás, suba e continue andando alternando as pernas.',
    mistakes:'Dar passos muito curtos, perdendo a ativação do glúteo.'},
  {id:'ex_elevacao_pelvica', name:'Elevação Pélvica', muscle:'gluteos', desc:'Isolamento de glúteos com apoio nas escápulas no banco.',
    execution:'Apoie as escápulas no banco, eleve o quadril contraindo os glúteos no topo e desça controlado.',
    mistakes:'Hiperextender a lombar no topo do movimento em vez de usar os glúteos.'},
  {id:'ex_hip_thrust', name:'Hip Thrust', muscle:'gluteos', desc:'Um dos exercícios mais eficazes para hipertrofia de glúteos, feito com barra sobre o quadril.',
    execution:'Costas superiores apoiadas no banco, empurre o quadril para cima contraindo os glúteos no topo e desça controlado.',
    mistakes:'Hiperextender a lombar em vez de contrair o glúteo e posicionar a barra no lugar errado do quadril.'},
  {id:'ex_abdutora', name:'Cadeira Abdutora', muscle:'gluteos', desc:'Isolamento do glúteo médio abrindo as pernas contra a resistência da máquina.',
    execution:'Sentado, abra as pernas contra a resistência contraindo o glúteo médio e retorne controlado.',
    mistakes:'Usar impulso do tronco e amplitude muito curta.'},
  {id:'ex_kickback', name:'Glúteo no Cabo (Kickback)', muscle:'gluteos', desc:'Isolamento unilateral de glúteo levando a perna para trás contra o cabo.',
    execution:'Com o cabo preso ao tornozelo, leve a perna para trás contraindo o glúteo, sem arquear a lombar.',
    mistakes:'Usar a lombar para gerar o movimento em vez do glúteo.'},
  {id:'ex_panturrilha_pe', name:'Panturrilha em Pé', muscle:'pernas', desc:'Exercício para a panturrilha (gastrocnêmio) realizado em pé.',
    execution:'Em pé na plataforma, eleve os calcanhares o máximo possível e desça controlado até alongar.',
    mistakes:'Fazer o movimento rápido demais, sem controlar a fase excêntrica.'},
  {id:'ex_panturrilha_sentada', name:'Panturrilha Sentada', muscle:'pernas', desc:'Exercício para a panturrilha (sóleo) realizado sentado.',
    execution:'Sentado, eleve os calcanhares contraindo a panturrilha e desça controlado até o alongamento.',
    mistakes:'Usar amplitude incompleta e não pausar na contração máxima.'},
  {id:'ex_desenvolvimento', name:'Desenvolvimento com Halteres', muscle:'ombros', desc:'Exercício composto para deltoides, com foco na porção anterior e lateral.',
    execution:'Sentado ou em pé, empurre os halteres para cima até quase estender o cotovelo, sem travar.',
    mistakes:'Arquear as costas e usar impulso das pernas para levantar o peso.'},
  {id:'ex_desenvolvimento_maquina', name:'Desenvolvimento Máquina', muscle:'ombros', desc:'Exercício guiado para deltoides, com menor exigência de estabilização.',
    execution:'Sentado com as costas apoiadas, empurre os manípulos para cima sem travar os cotovelos e desça controlado.',
    mistakes:'Ajustar o assento muito baixo ou alto, sobrecarregando o ombro.'},
  {id:'ex_elevacao_lateral', name:'Elevação Lateral', muscle:'ombros', desc:'Isolamento do deltoide lateral para largura de ombros.',
    execution:'Eleve os halteres lateralmente até a altura dos ombros, cotovelos levemente flexionados.',
    mistakes:'Usar impulso do corpo e elevar acima da linha dos ombros com carga excessiva.'},
  {id:'ex_rosca_direta', name:'Rosca Direta', muscle:'biceps', desc:'Exercício clássico de isolamento do bíceps braquial.',
    execution:'Cotovelos fixos ao lado do corpo, flexione o antebraço contraindo o bíceps e desça controlado.',
    mistakes:'Balançar o tronco para ajudar o movimento e mover os cotovelos para frente.'},
  {id:'ex_rosca_alternada', name:'Rosca Alternada', muscle:'biceps', desc:'Variação unilateral que permite maior foco em cada braço.',
    execution:'Alterne a flexão de cada braço, girando o punho levemente ao subir (supinação).',
    mistakes:'Usar embalo do ombro e não controlar a fase excêntrica.'},
  {id:'ex_rosca_martelo', name:'Rosca Martelo', muscle:'biceps', desc:'Variação com pegada neutra, trabalha bíceps e antebraço.',
    execution:'Com as palmas voltadas uma para a outra, flexione os cotovelos sem girar o punho.',
    mistakes:'Balançar o tronco e usar impulso do ombro para levantar o peso.'},
  {id:'ex_triceps_corda', name:'Tríceps Corda', muscle:'triceps', desc:'Exercício de isolamento do tríceps na polia alta com corda.',
    execution:'Cotovelos fixos junto ao corpo, estenda os braços separando a corda no final do movimento.',
    mistakes:'Afastar os cotovelos do corpo e usar o peso do tronco para empurrar.'},
  {id:'ex_triceps_testa', name:'Tríceps Testa', muscle:'triceps', desc:'Exercício com barra deitado, foco na cabeça longa do tríceps.',
    execution:'Deitado, flexione os cotovelos levando a barra em direção à testa e estenda de volta.',
    mistakes:'Abrir os cotovelos durante a descida e usar amplitude excessiva na cervical.'},
  {id:'ex_triceps_frances', name:'Tríceps Francês', muscle:'triceps', desc:'Exercício com halter atrás da cabeça, foco na cabeça longa do tríceps.',
    execution:'Segure o halter com as duas mãos atrás da cabeça, estenda os cotovelos para cima e desça controlado.',
    mistakes:'Abrir demais os cotovelos e descer o peso rápido demais atrás da cabeça.'},
  {id:'ex_abdominal', name:'Abdominal Supra', muscle:'abdomen', desc:'Exercício clássico para reto abdominal.',
    execution:'Deitado, flexione o tronco em direção aos joelhos contraindo o abdômen, sem puxar o pescoço.',
    mistakes:'Puxar a cabeça com as mãos e usar impulso em vez de contração abdominal.'},
  {id:'ex_abdominal_infra', name:'Abdominal Infra', muscle:'abdomen', desc:'Exercício focado na porção inferior do reto abdominal.',
    execution:'Deitado, eleve o quadril do chão levando os joelhos em direção ao peito contraindo o abdômen inferior.',
    mistakes:'Usar embalo das pernas em vez de contração abdominal.'},
  {id:'ex_elevacao_pernas', name:'Elevação de Pernas', muscle:'abdomen', desc:'Exercício para abdômen inferior, elevando as pernas estendidas ou flexionadas.',
    execution:'Deitado ou suspenso, eleve as pernas contraindo o abdômen e desça controlado sem tocar o chão.',
    mistakes:'Usar embalo e arquear a lombar durante a descida.'},
  {id:'ex_prancha', name:'Prancha Isométrica', muscle:'abdomen', desc:'Exercício isométrico para estabilidade do core.',
    execution:'Apoie antebraços e pontas dos pés, mantenha o corpo alinhado contraindo abdômen e glúteos.',
    mistakes:'Deixar o quadril cair ou subir demais, perdendo o alinhamento corporal.'},
  {id:'ex_prancha_lateral', name:'Prancha Lateral', muscle:'abdomen', desc:'Exercício isométrico para os oblíquos e estabilidade lateral do core.',
    execution:'Apoie um antebraço e a lateral do pé no chão, eleve o quadril mantendo o corpo alinhado.',
    mistakes:'Deixar o quadril cair para baixo, perdendo a ativação do oblíquo.'},
  {id:'ex_esteira', name:'Corrida na Esteira', muscle:'cardio', desc:'Atividade cardiovascular contínua para condicionamento e queima calórica.',
    execution:'Mantenha ritmo constante, postura ereta e respiração controlada durante todo o percurso.',
    mistakes:'Segurar no corrimão o tempo todo e usar passadas muito longas.'},
  {id:'ex_caminhada_inclinada', name:'Caminhada Inclinada', muscle:'cardio', desc:'Caminhada na esteira com inclinação, ótima para queima calórica com baixo impacto.',
    execution:'Ajuste a inclinação, caminhe em ritmo constante mantendo a postura ereta sem se apoiar no corrimão.',
    mistakes:'Segurar no corrimão, o que reduz o gasto calórico real do exercício.'},
  {id:'ex_bike', name:'Bicicleta Ergométrica', muscle:'cardio', desc:'Exercício cardiovascular de baixo impacto para pernas e sistema cardiorrespiratório.',
    execution:'Ajuste o selim na altura do quadril, pedale em ritmo constante controlando a resistência.',
    mistakes:'Selim muito baixo (sobrecarrega joelho) e postura curvada nas costas.'},
  {id:'ex_eliptico', name:'Elíptico', muscle:'cardio', desc:'Exercício cardiovascular de baixo impacto que trabalha membros superiores e inferiores.',
    execution:'Mantenha a postura ereta, pedale em movimento fluido usando também os braços nos apoios.',
    mistakes:'Apoiar todo o peso nos braços em vez de usar as pernas para o movimento.'},
  {id:'ex_escada', name:'Escada (Stairmaster)', muscle:'cardio', desc:'Exercício cardiovascular intenso que simula subir escadas continuamente.',
    execution:'Mantenha a postura ereta e passos curtos e constantes, evitando apoiar o peso todo nos braços.',
    mistakes:'Debruçar sobre o painel, reduzindo o trabalho das pernas.'},
  {id:'ex_pular_corda', name:'Pular Corda', muscle:'cardio', desc:'Exercício cardiovascular de alta intensidade que também trabalha coordenação.',
    execution:'Salte de forma leve, usando principalmente o movimento do punho para girar a corda.',
    mistakes:'Saltar muito alto gastando energia à toa e usar o ombro para girar a corda.'},
  {id:'ex_supino_declinado', name:'Supino Declinado', muscle:'peito', desc:'Variação do supino com foco na porção inferior do peitoral, feita com barra ou halteres.',
    execution:'Deite no banco declinado, mantenha escápulas encaixadas, desça a carga controlada até a linha baixa do peito e empurre sem travar os cotovelos.',
    mistakes:'Use amplitude confortável e evite deixar os ombros subirem ou perder o controle da descida.'},
  {id:'ex_crossover_alto', name:'Crossover Alto', muscle:'peito', desc:'Exercício no cabo para peitoral, com foco em contração e controle do movimento.',
    execution:'Com as polias altas, incline levemente o tronco, leve as mãos para frente e para baixo em arco e retorne devagar.',
    mistakes:'Mantenha cotovelos levemente flexionados; não transforme o movimento em empurrão de tríceps.'},
  {id:'ex_crossover_baixo', name:'Crossover Baixo', muscle:'peito', desc:'Variação do crossover que enfatiza a região superior do peitoral.',
    execution:'Com as polias baixas, eleve as mãos em arco até a frente do peito, contraindo o peitoral no final.',
    mistakes:'Evite balançar o tronco; escolha uma carga que permita controlar o cabo na volta.'},
  {id:'ex_flexao_bracos', name:'Flexão de Braços', muscle:'peito', desc:'Exercício com peso corporal para peito, ombros, tríceps e estabilidade do core.',
    execution:'Apoie mãos no chão na largura do peito, mantenha o corpo alinhado, desça controlando e empurre o chão para subir.',
    mistakes:'Contraia abdômen e glúteos para não deixar o quadril cair durante as repetições.'},
  {id:'ex_flexao_inclinada', name:'Flexão Inclinada', muscle:'peito', desc:'Variação mais acessível da flexão, feita com as mãos apoiadas em banco ou suporte.',
    execution:'Apoie as mãos em uma superfície firme, mantenha o corpo alinhado e aproxime o peito do apoio antes de subir.',
    mistakes:'Ótima para evoluir técnica; reduza a altura do apoio conforme ganhar força.'},
  {id:'ex_voador_cabo', name:'Voador no Cabo', muscle:'peito', desc:'Isolamento para peitoral que mantém tensão durante toda a amplitude.',
    execution:'Segure os cabos com braços semi-flexionados, abra até sentir alongamento e feche à frente do peito sem bater as mãos.',
    mistakes:'Controle a fase de volta; se os ombros incomodarem, reduza a amplitude.'},
  {id:'ex_puxada_neutra', name:'Puxada Pegada Neutra', muscle:'costas', desc:'Puxada vertical com pegada neutra, confortável para ombros e forte para dorsais.',
    execution:'Segure o triângulo ou pegadores neutros, puxe em direção à parte alta do peito e controle a subida.',
    mistakes:'Pense em levar os cotovelos para baixo; não puxe usando apenas os braços.'},
  {id:'ex_puxada_supinada', name:'Puxada Supinada', muscle:'costas', desc:'Variação da puxada com palmas voltadas para você, recrutando costas e bíceps.',
    execution:'Segure a barra em pegada supinada, mantenha peito aberto e puxe até a barra se aproximar do peito.',
    mistakes:'Evite jogar o tronco para trás; mantenha a escápula ativa antes de dobrar os cotovelos.'},
  {id:'ex_barra_fixa_assistida', name:'Barra Fixa Assistida', muscle:'costas', desc:'Exercício de puxada vertical com assistência, indicado para construir força com segurança.',
    execution:'Ajuste a assistência, segure a barra, suba levando o peito em direção à barra e desça controlando.',
    mistakes:'Use assistência suficiente para manter amplitude completa e evitar impulsos.'},
  {id:'ex_remada_cavalinho', name:'Remada Cavalinho', muscle:'costas', desc:'Remada com barra apoiada ou máquina, focada em espessura das costas.',
    execution:'Incline o tronco mantendo coluna neutra, puxe a carga em direção ao abdômen e aperte as escápulas.',
    mistakes:'Não arredonde a lombar; estabilize o tronco antes de puxar.'},
  {id:'ex_remada_maquina', name:'Remada Máquina', muscle:'costas', desc:'Remada guiada que ajuda a controlar trajetória e postura.',
    execution:'Ajuste o banco, apoie o peito se houver suporte, puxe os pegadores até a lateral do tronco e volte devagar.',
    mistakes:'Evite encolher ombros; foque em puxar com cotovelos e escápulas.'},
  {id:'ex_remada_serrote', name:'Remada Serrote', muscle:'costas', desc:'Remada unilateral com halter, útil para corrigir desequilíbrios entre lados.',
    execution:'Apoie uma mão e um joelho no banco, mantenha tronco firme e puxe o halter próximo ao quadril.',
    mistakes:'Não gire o tronco para levantar mais carga; a coluna deve ficar estável.'},
  {id:'ex_face_pull', name:'Face Pull', muscle:'costas', desc:'Exercício no cabo para parte alta das costas, deltoide posterior e saúde dos ombros.',
    execution:'Com a corda na altura do rosto, puxe em direção à testa abrindo as mãos e mantendo cotovelos altos.',
    mistakes:'Use carga leve/moderada e priorize controle, sem jogar a cabeça para frente.'},
  {id:'ex_crucifixo_inverso', name:'Crucifixo Inverso', muscle:'costas', desc:'Isolamento para deltoide posterior e região alta das costas.',
    execution:'Incline o tronco ou use máquina, abra os braços lateralmente e controle a volta sem perder a postura.',
    mistakes:'Evite subir os ombros; pense em abrir os braços com cotovelos levemente flexionados.'},
  {id:'ex_bom_dia', name:'Good Morning', muscle:'pernas', desc:'Exercício de dobradiça de quadril para posteriores, glúteos e lombar, feito com carga leve a moderada.',
    execution:'Com a barra apoiada nas costas, flexione pouco os joelhos, empurre o quadril para trás e retorne contraindo glúteos.',
    mistakes:'Aprenda com pouca carga; a coluna deve permanecer neutra o tempo todo.'},
  {id:'ex_terra_tradicional', name:'Levantamento Terra', muscle:'pernas', desc:'Exercício composto para cadeia posterior, glúteos, pernas e costas.',
    execution:'Com pés firmes, segure a barra próxima às canelas, empurre o chão e estenda quadril e joelhos até ficar em pé.',
    mistakes:'Mantenha a barra perto do corpo e não arredonde a lombar na saída do chão.'},
  {id:'ex_terra_sumo', name:'Levantamento Terra Sumô', muscle:'gluteos', desc:'Variação do terra com base aberta, enfatizando glúteos e adutores.',
    execution:'Afaste os pés, aponte levemente para fora, segure a barra entre as pernas e suba empurrando o chão.',
    mistakes:'Joelhos acompanham a direção dos pés; não deixe o quadril subir antes do tronco.'},
  {id:'ex_passada', name:'Passada', muscle:'gluteos', desc:'Exercício unilateral para glúteos e pernas, feito alternando passos à frente.',
    execution:'Dê um passo à frente, desça até formar ângulos confortáveis nos joelhos e retorne empurrando o chão.',
    mistakes:'Comece sem pressa; controle o equilíbrio antes de aumentar carga.'},
  {id:'ex_step_up', name:'Subida no Banco', muscle:'gluteos', desc:'Exercício unilateral que trabalha glúteos, quadríceps e estabilidade.',
    execution:'Apoie um pé no banco, suba empurrando pelo calcanhar da perna de cima e desça controlando.',
    mistakes:'Evite impulsionar demais com a perna de baixo; escolha altura segura para o joelho.'},
  {id:'ex_coice_maquina', name:'Glúteo Máquina', muscle:'gluteos', desc:'Isolamento de glúteo em máquina, bom para controle e foco muscular.',
    execution:'Apoie o tronco, posicione o pé na plataforma e empurre para trás contraindo o glúteo no final.',
    mistakes:'Não arqueie a lombar para ganhar amplitude; o movimento deve sair do quadril.'},
  {id:'ex_extensao_quadril_banco', name:'Extensão de Quadril no Banco', muscle:'gluteos', desc:'Exercício com peso corporal ou caneleira para ativação de glúteos.',
    execution:'Apoie o tronco no banco, mantenha o joelho flexionado e eleve a perna contraindo o glúteo.',
    mistakes:'Faça devagar e evite rodar o quadril para o lado durante a subida.'},
  {id:'ex_abducao_cabo', name:'Abdução no Cabo', muscle:'gluteos', desc:'Exercício unilateral para glúteo médio usando a polia baixa.',
    execution:'Prenda a tornozeleira, mantenha tronco firme e afaste a perna lateralmente sem inclinar o corpo.',
    mistakes:'Amplitude menor e controlada costuma funcionar melhor do que chutar alto sem controle.'},
  {id:'ex_abducao_elastico', name:'Abdução com Elástico', muscle:'gluteos', desc:'Ativação de glúteo médio com mini band, útil no aquecimento ou finalização.',
    execution:'Com o elástico acima dos joelhos ou tornozelos, afaste as pernas mantendo tensão constante.',
    mistakes:'Mantenha pés e joelhos alinhados; não deixe o elástico puxar os joelhos para dentro.'},
  {id:'ex_ponte_gluteos', name:'Ponte de Glúteos', muscle:'gluteos', desc:'Exercício de ativação de glúteos feito no chão, acessível e seguro.',
    execution:'Deite de barriga para cima, flexione joelhos, eleve o quadril e contraia glúteos no topo.',
    mistakes:'Não hiperestenda a lombar; pense em aproximar costelas e quadril.'},
  {id:'ex_sissy_squat', name:'Sissy Squat', muscle:'pernas', desc:'Exercício avançado para quadríceps, geralmente feito com apoio.',
    execution:'Segure um suporte, mantenha quadril estendido, flexione os joelhos deixando o tronco inclinar para trás e suba controlando.',
    mistakes:'Use pouca amplitude no início; evite se houver desconforto no joelho.'},
  {id:'ex_hack_squat', name:'Hack Squat', muscle:'pernas', desc:'Agachamento guiado em máquina com forte foco em quadríceps.',
    execution:'Apoie as costas, posicione os pés na plataforma, desça controlando e suba empurrando sem travar joelhos.',
    mistakes:'Ajuste a posição dos pés para não perder contato lombar com o encosto.'},
  {id:'ex_leg_press_unilateral', name:'Leg Press Unilateral', muscle:'pernas', desc:'Variação unilateral do leg press para corrigir diferenças entre pernas.',
    execution:'Use uma perna por vez, desça com controle até amplitude segura e empurre mantendo o joelho alinhado.',
    mistakes:'Use carga menor que no bilateral e não deixe o quadril rodar no assento.'},
  {id:'ex_extensora_unilateral', name:'Cadeira Extensora Unilateral', muscle:'pernas', desc:'Isolamento de quadríceps feito uma perna por vez.',
    execution:'Ajuste o encosto e o rolo, estenda um joelho até contrair o quadríceps e desça sem soltar a carga.',
    mistakes:'Controle os dois lados com a mesma técnica; não use impulso para terminar a repetição.'},
  {id:'ex_flexora_unilateral', name:'Flexora Unilateral', muscle:'pernas', desc:'Isolamento de posterior de coxa feito uma perna por vez.',
    execution:'Ajuste a máquina, flexione o joelho contraindo posterior e retorne lentamente até quase estender.',
    mistakes:'Evite levantar o quadril ou girar o corpo para compensar diferença de força.'},
  {id:'ex_panturrilha_legpress', name:'Panturrilha no Leg Press', muscle:'pernas', desc:'Variação de panturrilha feita na plataforma do leg press.',
    execution:'Com joelhos levemente flexionados, empurre a plataforma pela ponta dos pés e desça até alongar a panturrilha.',
    mistakes:'Movimento curto demais limita resultado; faça pausa rápida no topo e controle a descida.'},
  {id:'ex_arnold_press', name:'Desenvolvimento Arnold', muscle:'ombros', desc:'Variação do desenvolvimento com rotação dos halteres, trabalhando deltoides de forma ampla.',
    execution:'Comece com halteres à frente do rosto, palmas para você, gire enquanto empurra acima da cabeça e volte controlando.',
    mistakes:'Use carga moderada para não perder controle da rotação e não arquear a lombar.'},
  {id:'ex_elevacao_frontal', name:'Elevação Frontal', muscle:'ombros', desc:'Isolamento para deltoide anterior usando halteres, barra ou anilha.',
    execution:'Eleve a carga à frente até a altura dos ombros, com cotovelos levemente flexionados, e desça devagar.',
    mistakes:'Evite embalo do tronco; se precisar balançar, reduza a carga.'},
  {id:'ex_elevacao_lateral_cabo', name:'Elevação Lateral no Cabo', muscle:'ombros', desc:'Variação da elevação lateral com tensão constante pela polia.',
    execution:'Com a polia baixa, eleve o braço lateralmente até a linha do ombro e retorne controlando.',
    mistakes:'Mantenha o punho neutro e não encolha o ombro durante a subida.'},
  {id:'ex_remada_alta', name:'Remada Alta', muscle:'ombros', desc:'Exercício para deltoides e trapézio, feito com barra, halteres ou cabo.',
    execution:'Puxe a carga próxima ao corpo até a altura confortável, mantendo cotovelos apontados para fora.',
    mistakes:'Não force amplitude se houver incômodo no ombro; prefira pegada um pouco mais aberta.'},
  {id:'ex_encolhimento', name:'Encolhimento de Ombros', muscle:'ombros', desc:'Exercício para trapézio superior usando halteres, barra ou máquina.',
    execution:'Segure a carga ao lado do corpo e eleve os ombros para cima, pausando brevemente antes de descer.',
    mistakes:'Não gire os ombros; o movimento é para cima e para baixo com controle.'},
  {id:'ex_rosca_scott', name:'Rosca Scott', muscle:'biceps', desc:'Rosca no banco Scott que limita compensações e enfatiza o bíceps.',
    execution:'Apoie os braços no banco, flexione os cotovelos até contrair o bíceps e desça sem estender totalmente.',
    mistakes:'Evite soltar a carga no final; mantenha tensão e controle nos cotovelos.'},
  {id:'ex_rosca_inclinada', name:'Rosca Inclinada', muscle:'biceps', desc:'Rosca com halteres em banco inclinado, com maior alongamento do bíceps.',
    execution:'Sente no banco inclinado, deixe braços ao lado do corpo e flexione os cotovelos sem mover os ombros.',
    mistakes:'Use carga menor; o alongamento aumenta a exigência e pede controle.'},
  {id:'ex_rosca_cabo', name:'Rosca no Cabo', muscle:'biceps', desc:'Rosca na polia baixa com tensão constante durante o movimento.',
    execution:'Segure a barra ou corda, mantenha cotovelos junto ao corpo e flexione até contrair o bíceps.',
    mistakes:'Não leve os cotovelos para frente; mantenha postura firme.'},
  {id:'ex_rosca_concentrada', name:'Rosca Concentrada', muscle:'biceps', desc:'Rosca unilateral sentada, com foco em controle e contração do bíceps.',
    execution:'Apoie o braço na parte interna da coxa, flexione o cotovelo e desça devagar até quase estender.',
    mistakes:'Não use o tronco para ajudar; deixe o bíceps fazer o trabalho.'},
  {id:'ex_triceps_barra_reta', name:'Tríceps Barra Reta', muscle:'triceps', desc:'Extensão de tríceps na polia com barra reta, simples e eficiente.',
    execution:'Cotovelos fixos ao lado do corpo, empurre a barra para baixo até estender e volte controlando.',
    mistakes:'Não abra os cotovelos nem incline o tronco para transformar em empurrão.'},
  {id:'ex_triceps_coice', name:'Tríceps Coice', muscle:'triceps', desc:'Exercício unilateral de tríceps com halter ou cabo.',
    execution:'Incline o tronco, mantenha o cotovelo alto e estenda o braço para trás contraindo o tríceps.',
    mistakes:'Use carga leve; se o cotovelo cai, o tríceps perde tensão.'},
  {id:'ex_triceps_mergulho_banco', name:'Mergulho no Banco', muscle:'triceps', desc:'Exercício com peso corporal para tríceps, usando banco como apoio.',
    execution:'Apoie as mãos no banco, desça flexionando cotovelos e suba empurrando com os braços.',
    mistakes:'Mantenha ombros confortáveis; reduza amplitude se sentir pressão anterior no ombro.'},
  {id:'ex_triceps_maquina', name:'Tríceps Máquina', muscle:'triceps', desc:'Extensão guiada para tríceps com boa estabilidade e controle.',
    execution:'Ajuste o assento, apoie os braços e empurre os pegadores até estender os cotovelos.',
    mistakes:'Não tire as costas do encosto; controle a volta da carga.'},
  {id:'ex_abdominal_maquina', name:'Abdominal Máquina', muscle:'abdomen', desc:'Flexão de tronco guiada com carga ajustável para reto abdominal.',
    execution:'Ajuste a máquina, contraia o abdômen para aproximar costelas e quadril e volte sem relaxar totalmente.',
    mistakes:'Evite puxar com braços ou pescoço; o movimento deve vir do abdômen.'},
  {id:'ex_crunch_cabo', name:'Crunch no Cabo', muscle:'abdomen', desc:'Abdominal ajoelhado na polia, com resistência ajustável.',
    execution:'Segure a corda perto da cabeça, flexione o tronco levando costelas em direção ao quadril e retorne controlando.',
    mistakes:'Não sente sobre os calcanhares nem puxe com os braços; mantenha quadril estável.'},
  {id:'ex_dead_bug', name:'Dead Bug', muscle:'abdomen', desc:'Exercício de estabilidade para core, ótimo para controle lombar.',
    execution:'Deite de barriga para cima, eleve braços e pernas, estenda braço e perna opostos sem tirar a lombar do chão.',
    mistakes:'Faça devagar; pare se a lombar arquear durante a extensão.'},
  {id:'ex_bird_dog', name:'Bird Dog', muscle:'abdomen', desc:'Exercício de estabilidade que trabalha core, glúteos e controle postural.',
    execution:'Em quatro apoios, estenda braço e perna opostos mantendo o tronco parado, depois alterne os lados.',
    mistakes:'Evite girar o quadril; imagine um copo apoiado nas costas.'},
  {id:'ex_mountain_climber', name:'Mountain Climber', muscle:'cardio', desc:'Exercício dinâmico que combina core, cardio e coordenação.',
    execution:'Em posição de prancha, alterne os joelhos em direção ao peito mantendo mãos firmes no chão.',
    mistakes:'Mantenha quadril alinhado; velocidade só depois de controlar a postura.'},
  {id:'ex_burpee', name:'Burpee', muscle:'cardio', desc:'Exercício de corpo inteiro para condicionamento e gasto calórico.',
    execution:'Agache, apoie as mãos, leve os pés para trás, retorne para perto das mãos e levante ou salte.',
    mistakes:'Adapte sem salto se necessário; preserve técnica antes de buscar velocidade.'},
  {id:'ex_remo_ergometro', name:'Remo Ergométrico', muscle:'cardio', desc:'Cardio de baixo impacto que trabalha pernas, costas e braços.',
    execution:'Empurre com as pernas, incline levemente o tronco e puxe o cabo ao final, retornando na ordem inversa.',
    mistakes:'Não comece puxando com braços; a força principal vem das pernas.'},
  {id:'ex_air_bike', name:'Air Bike', muscle:'cardio', desc:'Bicicleta com braços móveis para condicionamento de alta intensidade.',
    execution:'Ajuste o banco, pedale e empurre/puxe as alças mantendo ritmo controlado.',
    mistakes:'Evite prender a respiração; use tiros curtos se a intensidade subir demais.'},
  {id:'ex_polichinelo', name:'Polichinelo', muscle:'cardio', desc:'Exercício simples de aquecimento e condicionamento, usando peso corporal.',
    execution:'Salte abrindo pernas e braços ao mesmo tempo, retornando ao centro em ritmo constante.',
    mistakes:'Aterrisse com leve flexão nos joelhos; adapte sem salto se houver impacto excessivo.'},
  {id:'ex_mobilidade_quadril', name:'Mobilidade de Quadril', muscle:'gluteos', desc:'Sequência leve para preparar quadril antes de treinos de pernas e glúteos.',
    execution:'Faça movimentos controlados de abertura, rotação e avanço do quadril por 30 a 60 segundos por lado.',
    mistakes:'Não force dor; a ideia é ganhar amplitude confortável antes da carga.'},
  {id:'ex_mobilidade_toracica', name:'Mobilidade Torácica', muscle:'costas', desc:'Exercício de mobilidade para coluna torácica, útil antes de puxadas e exercícios de ombro.',
    execution:'Em quatro apoios ou deitado de lado, gire o tronco abrindo o braço e acompanhe com o olhar.',
    mistakes:'Mantenha quadril estável e respire durante a rotação.'},
  {id:'ex_alongamento_posterior', name:'Alongamento de Posterior', muscle:'pernas', desc:'Alongamento para posteriores de coxa, usado em desaquecimento ou mobilidade leve.',
    execution:'Com uma perna estendida, incline o tronco mantendo coluna longa até sentir alongamento confortável.',
    mistakes:'Evite quicar ou forçar dor; mantenha respiração calma.'},
  {id:'ex_alongamento_peitoral', name:'Alongamento de Peitoral', muscle:'peito', desc:'Alongamento para peitoral e ombros, útil após treinos de empurrar.',
    execution:'Apoie o antebraço em uma parede ou portal e gire o tronco suavemente para abrir o peito.',
    mistakes:'Não force a articulação do ombro; ajuste a altura do braço se houver desconforto.'},
  {id:'ex_glute_drive_maquina', name:'Glute Drive Máquina', muscle:'gluteos', desc:'Exercício guiado para glúteos que simula o hip thrust com apoio e trajetória estável.',
    execution:'Ajuste o encosto e a faixa/apoio sobre o quadril, empurre a plataforma elevando o quadril e contraia os glúteos no topo antes de descer controlando.',
    mistakes:'Hiperestender a lombar no topo, deixar os pés longe demais e subir usando impulso em vez de contração dos glúteos.'},
  {id:'ex_passada_reversa_smith', name:'Passada Reversa no Smith', muscle:'gluteos', desc:'Variação guiada da passada reversa, ótima para glúteos e estabilidade unilateral.',
    execution:'Com a barra apoiada no Smith, dê um passo para trás, desça controlando o joelho de trás e suba empurrando o chão com a perna da frente.',
    mistakes:'Dar um passo curto demais, inclinar o tronco sem controle e deixar o joelho da frente colapsar para dentro.'},
  {id:'ex_extensao_45_gluteos', name:'Extensão 45° com Foco em Glúteos', muscle:'gluteos', desc:'Extensão de quadril no banco 45° com ênfase em glúteos e posteriores.',
    execution:'Apoie o quadril no banco, mantenha a coluna neutra, desça controlando e suba pensando em empurrar o quadril contra o apoio.',
    mistakes:'Subir hiperestendendo a lombar, olhar muito para cima e transformar o movimento em extensão das costas.'},
  {id:'ex_puxada_unilateral_cabo', name:'Puxada Unilateral no Cabo', muscle:'costas', desc:'Puxada vertical unilateral para dorsais, útil para corrigir diferenças entre os lados.',
    execution:'Segure o puxador com uma mão, puxe o cotovelo em direção ao quadril e controle a volta até alongar a dorsal.',
    mistakes:'Girar demais o tronco, puxar com o bíceps e perder a depressão da escápula.'},
  {id:'ex_remada_articulada_aberta', name:'Remada Articulada Pegada Aberta', muscle:'costas', desc:'Remada em máquina articulada com pegada aberta, focada em parte média e alta das costas.',
    execution:'Ajuste o peito no apoio, puxe os pegadores abrindo os cotovelos na linha confortável e contraia as escápulas.',
    mistakes:'Tirar o peito do apoio, encolher os ombros e usar balanço para completar a repetição.'},
  {id:'ex_rosca_bayesian_cabo', name:'Rosca Bayesian no Cabo', muscle:'biceps', desc:'Rosca unilateral no cabo com o braço ligeiramente atrás do corpo, enfatizando alongamento do bíceps.',
    execution:'De costas para a polia baixa, mantenha o cotovelo levemente atrás do tronco e flexione o braço sem avançar o ombro.',
    mistakes:'Deixar o cotovelo viajar para frente, usar carga alta demais e perder o controle na descida.'},
  {id:'ex_supino_inclinado_smith', name:'Supino Inclinado no Smith', muscle:'peito', desc:'Supino inclinado guiado no Smith, com foco em peitoral superior e estabilidade.',
    execution:'Ajuste o banco inclinado, posicione a barra na linha superior do peito, desça com controle e empurre sem travar os cotovelos.',
    mistakes:'Banco inclinado demais, punhos desalinhados e descer fora da linha do peito.'},
  {id:'ex_crucifixo_cabo', name:'Crucifixo no Cabo', muscle:'peito', desc:'Isolamento de peitoral no cabo com tensão constante durante todo o movimento.',
    execution:'Com cotovelos levemente flexionados, aproxime as mãos em arco à frente do peito e retorne até sentir alongamento confortável.',
    mistakes:'Dobrar demais os cotovelos, usar impulso do tronco e deixar o ombro avançar no final.'},
  {id:'ex_elevacao_lateral_maquina', name:'Elevação Lateral Máquina', muscle:'ombros', desc:'Isolamento do deltoide lateral em máquina, com trajetória estável e boa conexão muscular.',
    execution:'Ajuste o assento, apoie braços/cotovelos nos suportes e eleve até a linha dos ombros antes de descer controlando.',
    mistakes:'Encolher os ombros, usar carga alta demais e perder contato com o apoio.'},
  {id:'ex_triceps_frances_cabo', name:'Tríceps Francês no Cabo', muscle:'triceps', desc:'Extensão de tríceps acima da cabeça na polia, com foco na cabeça longa.',
    execution:'De costas para a polia, leve a corda acima da cabeça, mantenha cotovelos apontados à frente e estenda os braços controlando a volta.',
    mistakes:'Abrir demais os cotovelos, arquear a lombar e usar impulso do corpo.'},
  {id:'ex_triceps_unilateral_cabo', name:'Tríceps Unilateral no Cabo', muscle:'triceps', desc:'Extensão unilateral de tríceps na polia para trabalhar controle e simetria.',
    execution:'Com o cotovelo fixo ao lado do corpo, estenda o braço contra a polia e retorne devagar mantendo tensão.',
    mistakes:'Mover o cotovelo, inclinar o tronco para ajudar e acelerar a fase de volta.'},
  {id:'ex_agachamento_sumo_smith', name:'Agachamento Sumô no Smith', muscle:'gluteos', desc:'Agachamento sumô guiado no Smith, com foco em glúteos, adutores e coxas.',
    execution:'Posicione os pés mais abertos, ponta dos pés levemente para fora, desça mantendo joelhos alinhados e suba contraindo glúteos.',
    mistakes:'Deixar joelhos fecharem, apoiar carga excessiva na lombar e encurtar demais a amplitude.'},
  {id:'ex_remada_baixa_aberta', name:'Remada Baixa Aberta', muscle:'costas', desc:'Remada baixa com pegada aberta para enfatizar costas médias, romboides e deltoide posterior.',
    execution:'Puxe a barra em direção à região média do tronco, com cotovelos mais abertos e escápulas encaixando no final.',
    mistakes:'Balançar o tronco para trás, encolher ombros e puxar apenas com os braços.'},
  {id:'ex_rosca_martelo_corda', name:'Rosca Martelo na Corda', muscle:'biceps', desc:'Rosca na polia com corda e pegada neutra, trabalhando bíceps, braquial e antebraço.',
    execution:'Segure a corda na polia baixa, mantenha cotovelos junto ao corpo e flexione sem girar os punhos.',
    mistakes:'Abrir cotovelos, jogar ombros para frente e perder a tensão no final da descida.'},];

function findExercise(id){
  return EXERCISE_LIBRARY.find(e=>e.id===id) ||
    (typeof state!=='undefined' && state.customExercises && state.customExercises.find(e=>e.id===id));
}

// Modelos de treino padrão (usados na agenda semanal)
// Programa com ênfase estética em glúteos e pernas: 3 estímulos de glúteo,
// 1 dia forte de quadríceps, 2 dias de posterior, 1 de costas, 1 de peito,
// 1 de ombros, 1 de braços e abdômen 3x/semana.
const WORKOUT_TEMPLATES = {
  gluteo_posterior:{
    id:'gluteo_posterior', name:'Glúteos + Posterior', muscle:'gluteos', estimatedTime:75,
    description:'Treino pesado da semana para glúteos e posteriores, com foco em força e recomposição corporal.',
    warmup:'5-10 min de caminhada + mobilidade de quadril e 1-2 séries leves do primeiro exercício.',
    rir:'Nos principais, trabalhe com 1-2 RIR. Nos isoladores, controle a execução e evite roubar movimento.',
    exercises:[
      {exerciseId:'ex_levantamento_romeno', sets:4, reps:8, load:0, rest:150, note:'6-8 reps'},
      {exerciseId:'ex_glute_drive_maquina', sets:4, reps:10, load:0, rest:120, note:'8-10 reps'},
      {exerciseId:'ex_passada_reversa_smith', sets:3, reps:10, load:0, rest:90, note:'8-10 cada perna'},
      {exerciseId:'ex_cadeira_flexora', sets:3, reps:12, load:0, rest:75, note:'10-12 reps'},
      {exerciseId:'ex_extensao_45_gluteos', sets:3, reps:15, load:0, rest:75, note:'12-15 reps'},
      {exerciseId:'ex_abducao_cabo', sets:2, reps:20, load:0, rest:60, note:'15-20 cada lado'},
      {exerciseId:'ex_caminhada_inclinada', sets:1, reps:15, load:0, rest:0, timeUnit:'min'},
    ]
  },
  costas_biceps_abdomen:{
    id:'costas_biceps_abdomen', name:'Costas + Bíceps', muscle:'costas', estimatedTime:70,
    description:'Treino de largura e definição para costas, com bíceps no final.',
    warmup:'5-10 min de cardio leve + mobilidade de ombro e ativação escapular.',
    rir:'Mantenha 1-2 RIR na maioria das séries efetivas, sem perder controle das escápulas.',
    exercises:[
      {exerciseId:'ex_barra_fixa_assistida', sets:3, reps:10, load:0, rest:120, note:'6-10 reps'},
      {exerciseId:'ex_remada_cavalinho', sets:3, reps:10, load:0, rest:100, note:'8-10 reps'},
      {exerciseId:'ex_puxada_unilateral_cabo', sets:3, reps:12, load:0, rest:75, note:'10-12 cada lado'},
      {exerciseId:'ex_remada_articulada_aberta', sets:3, reps:12, load:0, rest:90, note:'10-12 reps'},
      {exerciseId:'ex_crucifixo_inverso', sets:3, reps:15, load:0, rest:60, note:'12-15 reps'},
      {exerciseId:'ex_rosca_scott', sets:3, reps:10, load:0, rest:75, note:'8-10 reps'},
      {exerciseId:'ex_rosca_bayesian_cabo', sets:2, reps:15, load:0, rest:60, note:'12-15 reps'},
      {exerciseId:'ex_eliptico', sets:1, reps:20, load:0, rest:0, timeUnit:'min', note:'ou bicicleta'},
    ]
  },
  quadriceps_panturrilha:{
    id:'quadriceps_panturrilha', name:'Quadríceps + Panturrilha', muscle:'pernas', estimatedTime:70,
    description:'Treino forte de coxas com foco em quadríceps, finalizando com panturrilhas.',
    warmup:'5-10 min de caminhada + mobilidade de quadril, tornozelo e joelho.',
    rir:'Priorize amplitude segura e controle. Não reduza demais o descanso nos exercícios grandes.',
    exercises:[
      {exerciseId:'ex_hack_squat', sets:4, reps:10, load:0, rest:150, note:'6-10 reps'},
      {exerciseId:'ex_leg_press_unilateral', sets:3, reps:12, load:0, rest:90, note:'10-12 cada perna'},
      {exerciseId:'ex_agachamento_bulgaro', sets:3, reps:10, load:0, rest:90, note:'foco em quadríceps, cada perna'},
      {exerciseId:'ex_extensora_unilateral', sets:3, reps:15, load:0, rest:60, note:'12-15 reps'},
      {exerciseId:'ex_panturrilha_pe', sets:4, reps:15, load:0, rest:60, note:'10-15 reps'},
      {exerciseId:'ex_panturrilha_sentada', sets:3, reps:20, load:0, rest:45, note:'15-20 reps'},
      {exerciseId:'ex_caminhada_inclinada', sets:1, reps:12, load:0, rest:0, timeUnit:'min', note:'10-15 min leve'},
    ]
  },
  peito_ombro_triceps:{
    id:'peito_ombro_triceps', name:'Ombros + Tríceps + Peito', muscle:'ombros', estimatedTime:70,
    description:'Treino de superiores com ombros mais presentes, seguido de tríceps e peito.',
    warmup:'5-10 min leve + mobilidade de ombro e séries leves de desenvolvimento.',
    rir:'Use 1-2 RIR nos exercícios principais e execução limpa nos isoladores.',
    exercises:[
      {exerciseId:'ex_desenvolvimento_maquina', sets:3, reps:10, load:0, rest:100, note:'8-10 reps'},
      {exerciseId:'ex_elevacao_lateral_cabo', sets:3, reps:15, load:0, rest:60, note:'12-15 cada lado'},
      {exerciseId:'ex_supino_inclinado_smith', sets:3, reps:10, load:0, rest:100, note:'8-10 reps'},
      {exerciseId:'ex_crucifixo_cabo', sets:2, reps:15, load:0, rest:60, note:'12-15 reps'},
      {exerciseId:'ex_elevacao_lateral_maquina', sets:2, reps:20, load:0, rest:60, note:'15-20 reps'},
      {exerciseId:'ex_triceps_frances_cabo', sets:3, reps:12, load:0, rest:75, note:'10-12 reps'},
      {exerciseId:'ex_triceps_unilateral_cabo', sets:3, reps:15, load:0, rest:60, note:'12-15 cada lado'},
      {exerciseId:'ex_eliptico', sets:1, reps:20, load:0, rest:0, timeUnit:'min', note:'ou caminhada inclinada'},
    ]
  },
  gluteo_enfase:{
    id:'gluteo_enfase', name:'Glúteos + Coxas', muscle:'gluteos', estimatedTime:75,
    description:'Treino de volume para glúteos e coxas, com estímulo diferente do treino pesado de segunda.',
    warmup:'5-10 min de caminhada + mobilidade de quadril e ativação de glúteos.',
    rir:'Foque em controle e amplitude. Na abdutora, use drop-set apenas na última série se estiver bem.',
    exercises:[
      {exerciseId:'ex_agachamento_sumo_smith', sets:3, reps:10, load:0, rest:100, note:'8-10 reps'},
      {exerciseId:'ex_step_up', sets:3, reps:10, load:0, rest:90, note:'cada perna'},
      {exerciseId:'ex_passada_reversa_smith', sets:3, reps:12, load:0, rest:90, note:'10-12 cada perna'},
      {exerciseId:'ex_flexora_unilateral', sets:3, reps:12, load:0, rest:75, note:'cada perna'},
      {exerciseId:'ex_coice_maquina', sets:3, reps:15, load:0, rest:60, note:'12-15 cada lado'},
      {exerciseId:'ex_abdutora', sets:3, reps:20, load:0, rest:60, note:'15-20 reps; drop-set na última'},
      {exerciseId:'ex_caminhada_inclinada', sets:1, reps:20, load:0, rest:0, timeUnit:'min', note:'15-20 min'},
    ]
  },
  full_body_condicionamento:{
    id:'full_body_condicionamento', name:'Costas + Braços + Abdômen', muscle:'costas', estimatedTime:70,
    description:'Segundo estímulo semanal de costas e braços, com abdômen e cardio moderado.',
    warmup:'5-10 min leve + mobilidade torácica e ativação escapular.',
    rir:'Sessão moderada: mantenha técnica, boa contração e descanso suficiente.',
    exercises:[
      {exerciseId:'ex_puxada_neutra', sets:3, reps:12, load:0, rest:90, note:'10-12 reps'},
      {exerciseId:'ex_remada_baixa_aberta', sets:3, reps:12, load:0, rest:90, note:'10-12 reps'},
      {exerciseId:'ex_face_pull', sets:3, reps:15, load:0, rest:60, note:'12-15 reps'},
      {exerciseId:'ex_elevacao_lateral', sets:3, reps:15, load:0, rest:60},
      {exerciseId:'ex_rosca_martelo_corda', sets:3, reps:12, load:0, rest:60, note:'10-12 reps'},
      {exerciseId:'ex_triceps_corda', sets:3, reps:12, load:0, rest:60, note:'10-12 reps'},
      {exerciseId:'ex_rosca_cabo', sets:2, reps:15, load:0, rest:45, note:'12-15 reps'},
      {exerciseId:'ex_triceps_frances_cabo', sets:2, reps:15, load:0, rest:45, note:'acima da cabeça, 12-15 reps'},
      {exerciseId:'ex_crunch_cabo', sets:3, reps:15, load:0, rest:45, note:'12-15 reps'},
      {exerciseId:'ex_eliptico', sets:1, reps:30, load:0, rest:0, timeUnit:'min', note:'25-30 min moderado'},
    ]
  },
  descanso:{
    id:'descanso', name:'Descanso', muscle:null, estimatedTime:0,
    description:'Dia de recuperação: caminhada leve, alongamentos, mobilidade e sono bem cuidado.',
    exercises:[]
  }
};
// Cronograma semanal padrão (0=Domingo ... 6=Sábado)
const DEFAULT_WEEK_PLAN = {
  1:'gluteo_posterior',           // Segunda — Glúteo + Posterior
  2:'costas_biceps_abdomen',      // Terça — Costas + Bíceps + Abdômen
  3:'quadriceps_panturrilha',     // Quarta — Quadríceps + Panturrilha
  4:'peito_ombro_triceps',        // Quinta — Peito + Ombro + Tríceps
  5:'gluteo_enfase',              // Sexta — Glúteo (ênfase) + Posterior
  6:'full_body_condicionamento',  // Sábado — Full Body + Condicionamento
  0:'descanso'                     // Domingo — Descanso ativo
};

// Informações gerais do programa (aquecimento, RIR, descanso, cardio, progressão)
const PROGRAM_INFO = {
  general:[
    {label:'Aquecimento', value:'5–10 min de caminhada + mobilidade da articulação treinada.', icon:'🔥'},
    {label:'Carga inicial', value:'60–70% da carga que você usava antes.', icon:'⚖️'},
    {label:'RIR (reserva)', value:'Termine cada série sentindo que daria 2–3 repetições a mais.', icon:'🎯'},
    {label:'Descanso entre séries', value:'2-3 min nos exercícios grandes e 60-90 s nos isoladores.', icon:'⏱'},
    {label:'Cardio', value:'105-120 min/semana, predominantemente moderado.', icon:'🏃'},
    {label:'Duração total', value:'60-80 minutos por sessão.', icon:'🕐'},
  ],
  volumeDistribution:[
    {label:'Glúteos', value:'2 estímulos principais (segunda e sexta)', icon:'🍑'},
    {label:'Quadríceps', value:'1 dia forte', icon:'🦵'},
    {label:'Posterior', value:'1 dia pesado + volume complementar', icon:'🍗'},
    {label:'Costas', value:'2 estímulos semanais', icon:'💪'},
    {label:'Peito', value:'1 estímulo dentro do treino de superiores', icon:'🩷'},
    {label:'Ombros', value:'2 estímulos, com foco estético', icon:'🟣'},
    {label:'Braços', value:'2 estímulos semanais', icon:'💥'},
    {label:'Abdômen', value:'1 sessão direta + ativação conforme necessidade', icon:'🔥'},
  ],
  progression:[
    {phase:'Semanas 1–2', points:['Priorize a técnica.','Não treine até a falha.','Use carga leve.']},
    {phase:'Semanas 3–4', points:['Aumente 5–10% da carga.','Pode adicionar uma série nos exercícios principais.']},
    {phase:'Semanas 5–6', points:['Treine próximo da falha (1–2 repetições de reserva).','Cardio de 20–25 minutos.']},
  ]
};

const WEEKDAY_NAMES = ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const WEEKDAY_SHORT = ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const MONTH_SHORT = ['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'];

const ACHIEVEMENTS = [
  {id:'first_workout', emoji:'🏅', name:'Primeiro Treino', desc:'Complete seu 1º treino', check:s=>s.history.length>=1},
  {id:'ten_workouts', emoji:'🏆', name:'10 Treinos', desc:'Complete 10 treinos', check:s=>s.history.length>=10},
  {id:'streak_30', emoji:'🔥', name:'30 Dias Seguidos', desc:'Mantenha 30 dias de streak', check:s=>s.streak>=30},
  {id:'load_100', emoji:'💪', name:'Levantar 100kg', desc:'Registre uma carga de 100kg ou mais', check:s=>s.history.some(h=>h.exercisesLog?.some(el=>el.sets?.some(st=>Number(st.weight)>=100)))},
  {id:'full_weeks', emoji:'⭐', name:'Semana Completa', desc:'Complete todos os treinos de uma semana', check:s=>s.fullWeeksCompleted>=1},
];

const MOODS = [
  {id:'excellent', emoji:'😀', label:'Excelente'},
  {id:'good', emoji:'🙂', label:'Bem'},
  {id:'tired', emoji:'😐', label:'Cansado'},
  {id:'exhausted', emoji:'😫', label:'Muito cansado'},
];
